name: 'GH Release Sync'
description: 'Automatically sync your new GitHub release version with your project'
branding:
    icon: 'at-sign'
    color: 'blue'
inputs:
  lang:
    description: 'Language of the project (e.g., rust, js, etc.)'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/chrisllontop/gh-release-sync:v1'
  env:
    INPUT_LANG: ${{ inputs.lang }}
