name: 'GH Release Sync'
description: 'Automatically sync your new GitHub release version with your project'
branding:
    icon: 'at-sign'
    color: 'blue'
inputs:
    lang:
        description: 'Language of the project (e.g., rust, js, etc.)'
        required: true
runs:
    using: 'node20'
    main: 'src/index.js'
